### ISSUE TITLE
Does Emplace() guarantee emplacing unique value?

### ISSUE THREAD

**Issue by miroslavp** [Wsm2110/Faster.Map#37]
Hi @Wsm2110 ,

I noticed that in the Get, Update, Remove, Contains methods, we loop through the metadata until we find an **empty slot**

` if (Vector128.Equals(source, _emptyBucketVector).ExtractMostSignificantBits() > 0)`

whereas in Emplace, AddOrUpdate and GetOrUpdate we check for both **empty or tombstone**
`mask = source.ExtractMostSignificantBits();`

I have the following questions about the algorithm:
1. Why do we check only for empty slot in the first case?
2. When we `Emplace`, we don't loop until we find an empty slot (-128). Does that mean that we can potentially add a duplicate if we find a tombstone first and put the value at that index?

**Comment by Wsm2110** [comment]
Hi mate,

1. Basically "empty" marks the end of a probchain. There is simply no need to go further. 
2. Havent looked at the code, but given a set of hashcollissions which hash to the same bucket (it might be possible)

**Comment by miroslavp** [comment]
> Hi mate,
> 
> 1. Basically "empty" marks the end of a probchain. There is simply no need to go further.
> 2. Havent looked at the code, but given a set of hashcollissions which hash to the same bucket (it might be possible)

Is this by design? Because I think this could be a problem for GetOrUpdate where we should add only if the key is not present. And I believe the code would check a whole vector and if the there's no h2 match in that vector, but there's a tombstone it will check no further and will insert the value at that tombstone

https://github.com/Wsm2110/Faster.Map/blob/0becfbab225715671a83d4f330cc735957fccd36/src/DenseMap.cs#L466-L486

**Comment by Wsm2110** [comment]
Yes, this is intentional. After reviewing it in detail, it’s clear that adding duplicate values can occur, but only under specific conditions: 

If the existing entry is located in a second probe group while the tombstone is in the first group, and we only compare the first group if the h2 hash matches. If this check fails and a tombstone is encountered, we skip comparing of the second group, even though it may contain a matching entry. Not sure if this makes sense.... Hence a duplicate is possible

 This happens because we don’t traverse the entire probe chain and add whenever we encounter a tombstone.

Ill add a fix when i have so spare time on my hands :)

**Comment by Wsm2110** [comment]
fixed
